# 是否启用首次登录提醒
enable-first-login-message: true

# 是否启用再次登录提醒
enable-rejoin-message: true

# 消息发送延迟时间（秒） - 控制欢迎消息的延迟发送
delay-seconds: 3

# 首次登录消息模板
# 支持 {player} 占位符、& 颜色代码
first-login-message: "&a欢迎回来，{player}！这是你的首次登录！"

# 再次登录消息模板
# 支持 {player}、{last_online}、{days}、{hours}、{minutes}、{seconds}
rejoin-message: "&b欢迎回来，{player}！你上次在线是 {last_online}，距今 {days} 天 {hours} 小时 {minutes} 分钟 {seconds} 秒。"
