name: LongTimeNoSee
version: 1.4.0
main: com.ixiangpro.longtimenosee.LongTimeNoSee
api-version: 1.13
author: iXiangPro
description: 记录玩家最后一次下线时间，并在重新登录时显示离线时长。
commands:
  ltns:
    description: LongTimeNoSee 主指令
    usage: /ltns <reload|check>
permissions:
  ltns.admin:
    description: 允许重载插件
    default: op
  ltns.check:
    description: 允许检查其他人的离线时间
    default: true
