name: Gradle Package

on:
  release:
    types: [created]
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[actions skip]') == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Capture build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: build/libs/

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
