name: Build and Release Plugin

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          NEW_VERSION="${VERSION}-build${BUILD_NUMBER}"
          
          # 修改 plugin.yml 中的版本号
          sed -i "s/version: .*/version: ${NEW_VERSION}/" src/main/resources/plugin.yml
          
          # 设置 Maven 的版本
          mvn versions:set -DnewVersion=$NEW_VERSION
          
          echo "PLUGIN_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      # 构建
      - name: Build with Maven
        run: mvn -B clean package shade:shade

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: longtimenosee
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: longtimenosee
          path: ./release

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
